### ISSUE TITLE
With the latest update (8.0.1.11), Accountant is no longer available in my Broker addon (Chocolate Bar)

### ISSUE THREAD

**Issue by gheldean** [DJDajn/Accountant#1] opened 2018-07-28 22:53 UTC
Not sure if it's a bug, or if I'm just missing something, so posting this as a comment... thanks!

**Comment by Fringetastic** [comment] 2018-07-29 02:42
Came to report this. Looked through interface options but didn't see a way to return it. Stepping back to 8.0.1.01 brought it back.

**Comment by DJDajn** [comment] 2018-07-29 09:00
What is not working with it? Is it that it wont show up at all, that it wont display the session/day/week/total gold or is it something else?
Would love a screenshot and an explanation on why it's not working as intended. :)

If it was about the missing session/day/week/total gold thing, is this what you where looking for? (screenshot)

![image](https://user-images.githubusercontent.com/4588530/43364615-fcd919e8-931d-11e8-8487-281cf923053c.png)

The amount on the left is the total value if you have checked "Show total on button (LDB)" in the settings.
The amount on the right is either the session/day/week or total amount.

So if the above was the thing you were looking for just write respond on this issue
If it wasn't, please come back with more info and a screenshot so I can take a look at it. :)

With regards,
Dajn

**Comment by Elbryan01** [comment] 2018-07-29 09:23
This is the problem, no option in titan panel to show accountant on the titan panel bar


![wowscrnshot_072918_111906](https://user-images.githubusercontent.com/41568310/43364790-9eb338fe-9321-11e8-993f-2634d477f92c.jpg)

**Comment by gheldean** [comment] 2018-07-29 09:33
Here is the same situation in Chocolate Bar, there is simply no option to select Accountant any longer
![image](https://user-images.githubusercontent.com/41842737/43364851-db45f300-92f0-11e8-8b28-fd249cc3c6a8.png)

**Comment by DJDajn** [comment] 2018-07-29 09:46
I'll push an updated version where accountant is visible in both Titan Panel and Chocolate Bar. 
![image](https://user-images.githubusercontent.com/4588530/43364891-dfe33d36-9323-11e8-99dd-66f5ce480e21.png)
![image](https://user-images.githubusercontent.com/4588530/43364892-e496a02a-9323-11e8-9131-e751229a708b.png)

If anything else comes up, please let me know. :)

With regards,
Dajn

**Comment by Urdui** [comment] 2018-07-29 17:21
Similar problem with Bazooka. Plugin is visible in settings and icon shows on LDB but no gold info presented on bar.

**Comment by DJDajn** [comment] 2018-07-29 17:57
Updated version should now be available on curse that addresses the broker addon issues (after 8 hours of waiting for it to be approved).

Please let me know if the new version works. :)

With regards, 
Dajn

**Comment by DJDajn** [comment] 2018-07-29 20:03
Closing this issue, if you still have problems with the newest version (8.0.1.12), make a new issue.

With regards,
Dajn

**Closed as completed by DJDajn** 2018-07-29 20:03 UTC
Labels: bug
